'use strict';

export const FETCH_COFFEE_VARIETIES_REQUEST = 'FETCH_COFFEE_VARIETIES_REQUEST';
export const FETCH_COFFEE_VARIETIES_SUCCESS = 'FETCH_COFFEE_VARIETIES_SUCCESS';
export const FETCH_COFFEE_VARIETIES_FAIL = 'FETCH_COFFEE_VARIETIES_FAIL';

export function fetchCoffeeVarieties() {
  return {
    type: [
      FETCH_COFFEE_VARIETIES_REQUEST,
      FETCH_COFFEE_VARIETIES_SUCCESS,
      FETCH_COFFEE_VARIETIES_FAIL
    ]
  };
}
